def DNAComplement(dna):
    '''
    First Reveresed the DNA sequence and then Complimented the DNA Nucleotides
    :param dna:
    :return dnaC:
    '''
    dna = dna[::-1]
    dnaC = dna.replace('C','0')
    dnaC = dnaC.replace('G','C')
    dnaC = dnaC.replace('0', 'G')
    dnaC = dnaC.replace('A', '0')
    dnaC = dnaC.replace('T', 'A')
    dnaC = dnaC.replace('0', 'T')
    return dnaC



# print DNAComplement("CTAGTCACTCTCACAAGCTACCGCTGGTAAGGTTGCGTGAGAACGAGTTTGCAACAACAAGGGAACCGCAATAGATAGTGGCCGTGGAACGCGGTATAGACTTTCCCTATACCTTCCCTGAACCAGATTTGCCCGGGCAGGGAAAAATGCCGGAGGGAGCCTACTTTTGTACAGTTAACGTCTCAGGGCGAGGTCCACACCCGGTCTTAGCTGTACTTCTTCCTAGAGTCGCAAAATCAGTTCGTCGGGGGAGGGGCCCTTTTCGTTAAAACCACAGATCGGGCTCGATCGTCGCCTCATGCCGTTGTGTGGGTCTGTAACGGGGTGAGTTAAAAGAGTTATAGGTACGCTGAATCCCTCATTTCATGCTGACTGCGGTTGGCATTTTAACCTTGAGTTAGGTAAGCAATTAGAACCTAATGGGTAGCCACTCAAAGGCCTACAACTGCTGTTCGTCATAACGTGGGCGTGTCCGCAACATATGCTGATGAGGGTGAATCACCATTTAGCGAAAAGTAGGAGATGCCAGGGTGACATGCTCGATAGCACCATTAATCTGTTGAGCGCTTTACTGATGTCTCAGACTATTTTTGGCAGGCGACCTAGGGTGCCTCAAAGACAATGTACGCTACTCATGTGATTAAGCGGCATAAGAATCAGCAGTAAGTCTCCCTAGTCGACTGTCCCCGGGAACGCGGAAATTGAGTTGGTGCATGAAGACCGGTGATCCCCTCCCCGGGTTCAAGCTACGCATTACGGCATTCATGCCTCGCGACCCTCCAGTATGTAATGGCTCTGAAACCCCTCGCTTTACTACGCGTTATGCCACAAGCCTCGGTTTATGTGTAGGACGCGATTAAGCTGACGT")